//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Terminal1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Класс билета.
    /// </summary>
    // *** Start programmer edit section *** (КлассБилета CustomAttributes)

    // *** End programmer edit section *** (КлассБилета CustomAttributes)
    [AutoAltered()]
    [Caption("Класс билета")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлассБилетаE", new string[] {
            "Класс as \'Класс\'",
            "Место as \'Место\'"})]
    [View("КлассБилетаL", new string[] {
            "Класс as \'Класс\'",
            "Место as \'Место\'"})]
    public class КлассБилета : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Terminal1.ВидБилета fКласс;
        
        private string fМесто;
        
        // *** Start programmer edit section *** (КлассБилета CustomMembers)

        // *** End programmer edit section *** (КлассБилета CustomMembers)

        
        /// <summary>
        /// Класс.
        /// </summary>
        // *** Start programmer edit section *** (КлассБилета.Класс CustomAttributes)

        // *** End programmer edit section *** (КлассБилета.Класс CustomAttributes)
        public virtual IIS.Terminal1.ВидБилета Класс
        {
            get
            {
                // *** Start programmer edit section *** (КлассБилета.Класс Get start)

                // *** End programmer edit section *** (КлассБилета.Класс Get start)
                IIS.Terminal1.ВидБилета result = this.fКласс;
                // *** Start programmer edit section *** (КлассБилета.Класс Get end)

                // *** End programmer edit section *** (КлассБилета.Класс Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КлассБилета.Класс Set start)

                // *** End programmer edit section *** (КлассБилета.Класс Set start)
                this.fКласс = value;
                // *** Start programmer edit section *** (КлассБилета.Класс Set end)

                // *** End programmer edit section *** (КлассБилета.Класс Set end)
            }
        }
        
        /// <summary>
        /// Место.
        /// </summary>
        // *** Start programmer edit section *** (КлассБилета.Место CustomAttributes)

        // *** End programmer edit section *** (КлассБилета.Место CustomAttributes)
        [StrLen(255)]
        public virtual string Место
        {
            get
            {
                // *** Start programmer edit section *** (КлассБилета.Место Get start)

                // *** End programmer edit section *** (КлассБилета.Место Get start)
                string result = this.fМесто;
                // *** Start programmer edit section *** (КлассБилета.Место Get end)

                // *** End programmer edit section *** (КлассБилета.Место Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КлассБилета.Место Set start)

                // *** End programmer edit section *** (КлассБилета.Место Set start)
                this.fМесто = value;
                // *** Start programmer edit section *** (КлассБилета.Место Set end)

                // *** End programmer edit section *** (КлассБилета.Место Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КлассБилетаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлассБилетаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлассБилетаE", typeof(IIS.Terminal1.КлассБилета));
                }
            }
            
            /// <summary>
            /// "КлассБилетаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлассБилетаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлассБилетаL", typeof(IIS.Terminal1.КлассБилета));
                }
            }
        }
    }
}
