//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Terminal1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Коды.
    /// </summary>
    // *** Start programmer edit section *** (Коды CustomAttributes)

    // *** End programmer edit section *** (Коды CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КодыE", new string[] {
            "КодБрони as \'Код брони\'"})]
    [View("КодыL", new string[] {
            "КодБрони as \'Код брони\'"})]
    public class Коды : ICSSoft.STORMNET.DataObject
    {
        
        private string fКодБрони;
        
        // *** Start programmer edit section *** (Коды CustomMembers)

        // *** End programmer edit section *** (Коды CustomMembers)

        
        /// <summary>
        /// КодБрони.
        /// </summary>
        // *** Start programmer edit section *** (Коды.КодБрони CustomAttributes)

        // *** End programmer edit section *** (Коды.КодБрони CustomAttributes)
        [StrLen(255)]
        public virtual string КодБрони
        {
            get
            {
                // *** Start programmer edit section *** (Коды.КодБрони Get start)

                // *** End programmer edit section *** (Коды.КодБрони Get start)
                string result = this.fКодБрони;
                // *** Start programmer edit section *** (Коды.КодБрони Get end)

                // *** End programmer edit section *** (Коды.КодБрони Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Коды.КодБрони Set start)

                // *** End programmer edit section *** (Коды.КодБрони Set start)
                this.fКодБрони = value;
                // *** Start programmer edit section *** (Коды.КодБрони Set end)

                // *** End programmer edit section *** (Коды.КодБрони Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КодыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КодыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КодыE", typeof(IIS.Terminal1.Коды));
                }
            }
            
            /// <summary>
            /// "КодыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КодыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КодыL", typeof(IIS.Terminal1.Коды));
                }
            }
        }
    }
}
