//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Terminal1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Пассажир.
    /// </summary>
    // *** Start programmer edit section *** (Пассажир CustomAttributes)

    // *** End programmer edit section *** (Пассажир CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПассажирE", new string[] {
            "ФИО as \'ФИО\'",
            "КлассБилета as \'Класс билета\'",
            "КлассБилета.Место as \'Место\'",
            "Коды as \'Коды\'",
            "Коды.КодБрони as \'Код брони\'"}, Hidden=new string[] {
            "КлассБилета.Место",
            "Коды.КодБрони"})]
    [MasterViewDefineAttribute("ПассажирE", "КлассБилета", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Место")]
    [MasterViewDefineAttribute("ПассажирE", "Коды", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "КодБрони")]
    [View("ПассажирL", new string[] {
            "ФИО as \'ФИО\'",
            "Коды.КодБрони as \'Код брони\'",
            "КлассБилета.Место as \'Место\'"})]
    public class Пассажир : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private IIS.Terminal1.КлассБилета fКлассБилета;
        
        private IIS.Terminal1.Коды fКоды;
        
        // *** Start programmer edit section *** (Пассажир CustomMembers)

        // *** End programmer edit section *** (Пассажир CustomMembers)

        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Пассажир.ФИО CustomAttributes)

        // *** End programmer edit section *** (Пассажир.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Пассажир.ФИО Get start)

                // *** End programmer edit section *** (Пассажир.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Пассажир.ФИО Get end)

                // *** End programmer edit section *** (Пассажир.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Пассажир.ФИО Set start)

                // *** End programmer edit section *** (Пассажир.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Пассажир.ФИО Set end)

                // *** End programmer edit section *** (Пассажир.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Пассажир.
        /// </summary>
        // *** Start programmer edit section *** (Пассажир.КлассБилета CustomAttributes)

        // *** End programmer edit section *** (Пассажир.КлассБилета CustomAttributes)
        [PropertyStorage(new string[] {
                "КлассБилета"})]
        [NotNull()]
        public virtual IIS.Terminal1.КлассБилета КлассБилета
        {
            get
            {
                // *** Start programmer edit section *** (Пассажир.КлассБилета Get start)

                // *** End programmer edit section *** (Пассажир.КлассБилета Get start)
                IIS.Terminal1.КлассБилета result = this.fКлассБилета;
                // *** Start programmer edit section *** (Пассажир.КлассБилета Get end)

                // *** End programmer edit section *** (Пассажир.КлассБилета Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Пассажир.КлассБилета Set start)

                // *** End programmer edit section *** (Пассажир.КлассБилета Set start)
                this.fКлассБилета = value;
                // *** Start programmer edit section *** (Пассажир.КлассБилета Set end)

                // *** End programmer edit section *** (Пассажир.КлассБилета Set end)
            }
        }
        
        /// <summary>
        /// Пассажир.
        /// </summary>
        // *** Start programmer edit section *** (Пассажир.Коды CustomAttributes)

        // *** End programmer edit section *** (Пассажир.Коды CustomAttributes)
        [PropertyStorage(new string[] {
                "Коды"})]
        [NotNull()]
        public virtual IIS.Terminal1.Коды Коды
        {
            get
            {
                // *** Start programmer edit section *** (Пассажир.Коды Get start)

                // *** End programmer edit section *** (Пассажир.Коды Get start)
                IIS.Terminal1.Коды result = this.fКоды;
                // *** Start programmer edit section *** (Пассажир.Коды Get end)

                // *** End programmer edit section *** (Пассажир.Коды Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Пассажир.Коды Set start)

                // *** End programmer edit section *** (Пассажир.Коды Set start)
                this.fКоды = value;
                // *** Start programmer edit section *** (Пассажир.Коды Set end)

                // *** End programmer edit section *** (Пассажир.Коды Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПассажирE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПассажирE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПассажирE", typeof(IIS.Terminal1.Пассажир));
                }
            }
            
            /// <summary>
            /// "ПассажирL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПассажирL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПассажирL", typeof(IIS.Terminal1.Пассажир));
                }
            }
        }
    }
}
