//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Terminal1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Посад талон.
    /// </summary>
    // *** Start programmer edit section *** (ПосадТалон CustomAttributes)

    // *** End programmer edit section *** (ПосадТалон CustomAttributes)
    [AutoAltered()]
    [Caption("Посад талон")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПосадТалонE", new string[] {
            "Пассажир as \'Пассажир\'",
            "Пассажир.ФИО as \'ФИО\'",
            "Рейс as \'Рейс\'",
            "Рейс.Куда as \'Куда\'"}, Hidden=new string[] {
            "Пассажир.ФИО",
            "Рейс.Куда"})]
    [MasterViewDefineAttribute("ПосадТалонE", "Пассажир", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("ПосадТалонE", "Рейс", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Куда")]
    [View("ПосадТалонL", new string[] {
            "Пассажир.ФИО as \'ФИО\'",
            "Рейс.Куда as \'Куда\'"})]
    public class ПосадТалон : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Terminal1.Пассажир fПассажир;
        
        private IIS.Terminal1.Рейс fРейс;
        
        // *** Start programmer edit section *** (ПосадТалон CustomMembers)

        // *** End programmer edit section *** (ПосадТалон CustomMembers)

        
        /// <summary>
        /// Посад талон.
        /// </summary>
        // *** Start programmer edit section *** (ПосадТалон.Пассажир CustomAttributes)

        // *** End programmer edit section *** (ПосадТалон.Пассажир CustomAttributes)
        [PropertyStorage(new string[] {
                "Пассажир"})]
        [NotNull()]
        public virtual IIS.Terminal1.Пассажир Пассажир
        {
            get
            {
                // *** Start programmer edit section *** (ПосадТалон.Пассажир Get start)

                // *** End programmer edit section *** (ПосадТалон.Пассажир Get start)
                IIS.Terminal1.Пассажир result = this.fПассажир;
                // *** Start programmer edit section *** (ПосадТалон.Пассажир Get end)

                // *** End programmer edit section *** (ПосадТалон.Пассажир Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПосадТалон.Пассажир Set start)

                // *** End programmer edit section *** (ПосадТалон.Пассажир Set start)
                this.fПассажир = value;
                // *** Start programmer edit section *** (ПосадТалон.Пассажир Set end)

                // *** End programmer edit section *** (ПосадТалон.Пассажир Set end)
            }
        }
        
        /// <summary>
        /// Посад талон.
        /// </summary>
        // *** Start programmer edit section *** (ПосадТалон.Рейс CustomAttributes)

        // *** End programmer edit section *** (ПосадТалон.Рейс CustomAttributes)
        [PropertyStorage(new string[] {
                "Рейс"})]
        [NotNull()]
        public virtual IIS.Terminal1.Рейс Рейс
        {
            get
            {
                // *** Start programmer edit section *** (ПосадТалон.Рейс Get start)

                // *** End programmer edit section *** (ПосадТалон.Рейс Get start)
                IIS.Terminal1.Рейс result = this.fРейс;
                // *** Start programmer edit section *** (ПосадТалон.Рейс Get end)

                // *** End programmer edit section *** (ПосадТалон.Рейс Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПосадТалон.Рейс Set start)

                // *** End programmer edit section *** (ПосадТалон.Рейс Set start)
                this.fРейс = value;
                // *** Start programmer edit section *** (ПосадТалон.Рейс Set end)

                // *** End programmer edit section *** (ПосадТалон.Рейс Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПосадТалонE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПосадТалонE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПосадТалонE", typeof(IIS.Terminal1.ПосадТалон));
                }
            }
            
            /// <summary>
            /// "ПосадТалонL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПосадТалонL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПосадТалонL", typeof(IIS.Terminal1.ПосадТалон));
                }
            }
        }
    }
}
